export const ADMIN_ROUTE ='/admin'
export const LOGIN_ROUTE ='/login'
export const REGISTRATION_ROUTE ='/reg'
export const SHOP_ROUTE ='/shop'
export const BASKET_ROUTE ='/basket'
export const NOTFOUND_ROUTE ='/nf'
export const DEVICE_ROUTE ='/device'